#!/usr/bin/env bash
# Script: htb
# Author: Jacco van Buuren
# License: BSD 3-clause.

# Description: HackTheBox connect script.
#   This scripts connect to HTB with openvpn and will setup a directory named after the box.
#   Nmap is run as soon as the connection is established.

# Parameters:
# 1. To connect to HTB: OpenVPN-file
# 2. Box name: String.htb
# 3. IP-address of the box: 10.129.x.y

# This script will try to:
# 1. connect to HTB, if not already connected, reconnect if required.
# 2. When the connection is up, ping box IP-addr or reconnect until it does.
# 3. If the box has an entry in /etc/hosts: Replace IP-addr with current, if not add IP-addr and name to /etc/hosts
# 4. mkdir /htb/<name-of-box> if not already there
# 5. run nmap -A -v -n -vv -p- -Pn --open /htb/<name>/full.nmap IP-addr
# 6. run whatever

# -- Globals, constants

MYHTBDIR="/htb"

OVPN="${1:-$HOME/openvpn/hackthebox.ovpn}"
BOXNAME="${2}"
IP="${3}"

ISCONNECTED=0
ROUTE=""
RTR=""
NIC=""

HTBRTR="10.10.14.1"
HTBNIC="tun0"
VPNSLEEP=10
KILLSLEEP=5
PINGSLEEP=1
PINGAMOUNT=10

HOSTS="/etc/hosts"

# -- Functions

usage() {
	cat <<-___EOF___
	Sorry. Not yet implemented.
	___EOF___
	return 0
}

# -- Parameter parsing

if [ "$1" = "-h" -o "$1" = "--help" ]; then
	usage
	exit 0
fi

# -- Sanity checking

if [ $# -ne 3 ]; then
	echo "[x] Missing a parameter. Use -h or --help for help. Aborted" >&2
	exit 1
fi

if [ ! -r "$OVPN" ]; then
	echo "[x] $OVPN is not readable. Does it exist? Aborted" >&2
	exit 1
fi

# -- Main

# Connect to HTB

echo "[+] Connecting to HTB"
while [ $ISCONNECTED -eq 0 ]; do
	# Check current state first. If we have a route from $HTBNIC to $HTBRTR we could be good to go.
	ROUTE=$(ip route get "$IP" | awk '{print $3 " " $5}' | grep '^[0-9]' | head -n 1)
	RTR=$(echo "$ROUTE" | awk '{print $1}')
	NIC=$(echo "$ROUTE" | awk '{print $2}')
	if [ "$NIC" = "$HTBNIC" -a "$RTR" = "$HTBRTR" ]; then
		# Make double sure there's an openvpn running with a filename for connection details
		echo "[+] Connection looks good. $RTR and $NIC are as expected."
		RUNNINGVPN="$(basename $(ps ax | grep "openvp[n]" | awk '$5 == "openvpn" { print $NF }' | head -n 1))"
		if [ "x${RUNNINGVPN}x" = "xx" ]; then
			# If there's no openvpn running, even with RTR and NIC matching HTBs', then there's something odd going on.
			echo ""
			echo "[x] Conflicting routes to be able to connect to HTB. Aborted" >&2
			exit 1
		fi
		# Check if the openvpn filename resembles the filename given; We might be on the wrong vpn!
		OURVPN="$(basename $OVPN)"
		if [ "x${RUNNINGVPN}x" = "x${OURVPN}x" ]; then
			# The openvpn running was started with a similar named vpn file. Assume it's the same.
			# So, it appears we're connected, a ping to the box **MUST** work, but retry $PINGCOuNT times before restarting.
			echo "[+] VPN should be good. $IP should respond to pings..."
			PINGCOUNT="$PINGAMOUNT"
			while [ $ISCONNECTED -eq 0 -a $PINGCOUNT -gt 1 ]; do
				ping -q -c 1 -w 3 -W 3 "$IP" &>/dev/null && \
					ISCONNECTED=1
				printf "."
				PINGCOUNT=$((PINGCOUNT - 1))
				sleep "$PINGSLEEP"
			done
			# If no ping was answered, restart openvpn.
			if [ $ISCONNECTED -eq 0 ]; then
				echo ""
				echo "[W] Box did not respond. Restarting openvpn." >&2
				pkill -KILL openvpn &>/dev/null
				sleep "$KILLSLEEP"
				openvpn "$OVPN" &>/dev/null &
				sleep "$VPNSLEEP"
			fi
		else
			# The running openvpn does not match the ovpn filename, assuming it's a different HTB-vpn. We need to reconnect.
			echo "[W] We're on the wrong HTB-vpn, restarting openvpn" >&2
			pkill -KILL openvpn &>/dev/null
			sleep "$KILLSLEEP"
			# Make the connection, but stay in the loop until the box responds to a ping.
			openvpn "$OVPN" &>/dev/null &
			sleep "$VPNSLEEP"
		fi
	else
		# The route to HTB appears missing. If not connected, but the interface to the htb-vpn exists, kill openvpn.
		echo "[+] No existing route found. Establishing connection..."
		ip -o a sh dev "$HTBNIC" &>/dev/null && \
			{ pkill -KILL openvpn &>/dev/null; sleep "$KILLSLEEP"; }
		# Make the connection to HTB, but stay in the loop until the box responds to a ping.
		openvpn "$OVPN" &>/dev/null &
		sleep "$VPNSLEEP"
	fi
done
echo ""
echo "[+] Connected!"

# Add or modify host entry in /etc/hosts

grep -w "$BOXNAME" "$HOSTS" &>/dev/null
if [ $? -eq 0 ]; then
	# The box is already in /etc/hosts: Modify the entry to match the current IP-address
	echo "[+] Modifying $HOSTS to match $BOXNAME to $IP"
	#sed -i "/$BOXNAME/s/^[^[:space:]]*\(.*$BOXNAME.*$\)/$IP\t\1/" "$HOSTS"
	sed -i "/$BOXNAME/s/^[^[:space:]]*\($BOXNAME.*\)$/$IP\t\1/" "$HOSTS"
else
	# The box is not in /etc/hosts: Add the IP-address and boxname to /etc/hosts
	echo "[+] Adding $IP and $BOXNAME to $HOSTS"
	printf "%s\t%s" "$IP" "$BOXNAME" >> /etc/hosts
fi

# Create directory and start nmap

HTBDIR="$MYHTBDIR/$BOXNAME"
mkdir -p "$HTBDIR" &>/dev/null

touch "$HTBDIR/$IP" || \
	{ echo "[x] Failed to write in $HTBDIR. Aborted" >&2; exit 1; }

nmap -A -p- -n -vv -oA "$HTBDIR/full" "$IP"




